---
abstract: 'p5u extension to view change logs'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: P5U::Command::Changes
name: P5U-Command-Changes
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CPAN::Changes: 0
  JSON: 0
  LWP::UserAgent: 0
  Module::Info: 0
  P5U: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=P5U-Command-Changes
  homepage: https://metacpan.org/release/P5U-Command-Changes
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-p5u-command-changes
version: 0.001
